import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google";
import "./globals.css";
import StoreProvider from "./StoreProvider";
import { Toaster } from "@/components/ui/toaster";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es" suppressHydrationWarning>
      <body
        className={`${fontSans.variable} antialiased`}
      >
        <StoreProvider>
          <div className="flex min-h-screen flex-col bg-black">
            <div className="min-h-screen bg-black text-white">
              <main className="container mx-auto">
                {children}
              </main>
              <Toaster />
            </div>
          </div>
        </StoreProvider>
      </body>
    </html>
  );
}
